### ISSUE TITLE
Private repo

### ISSUE THREAD

**Issue by senthilkumar1729** [HAC-2020/radadiyamohit81#1]
We had asked participants to make the repository public when HAC was over to make it easier for judges to access, it seems like your repository has stayed private.

I have gone ahead and made it public for now and will return it to private once judging session is over 👍

**Comment by radadiyamohit81** [comment]
OK thank you for supporting me. And when the winner list declared.

**Comment by senthilkumar1729** [comment]
Hey, the winners were declared yesterday on HAC's discord - [https://discord.com/invite/9g9eZxc]( https://discord.com/invite/9g9eZxc ) I request you to check it out and get involved as soon as possible!
